// Adapt — AI-generated training plan endpoint
//
// POST a user's onboarding inputs; get back a structured periodized plan
// generated by Mistral Large with heavy methodology priming (Friel block
// periodization, Daniels VDOT pacing, Seiler 80/20 polarized intensity,
// race-specific tapers, discipline-specific session vocabulary).
//
// Returns deterministic JSON the frontend can render. Validates the AI's
// output against safety guardrails (sane hours, no zero rest weeks, no
// week-over-week jumps > 30%, at least one rest day per week). On any
// failure (malformed JSON, validation reject, network error) the frontend
// falls back to the rule-based generator so users always get *something*.

export const config = { runtime: 'edge' };

const MISTRAL_URL = 'https://api.mistral.ai/v1/chat/completions';
const PLAN_MODEL = 'mistral-large-latest'; // quality > speed for plan generation
const MAX_TOKENS = 4500;                    // 6 weeks of detail fits in ~3000-4000 tokens
const REQUEST_TIMEOUT_MS = 45000;

// Plan generation is the most expensive call in this app (~$0.025-0.04 per
// invocation with Mistral Large). Cap per-IP attempts hard. The map is
// in-memory and Edge functions are stateless across instances/cold starts —
// this is best-effort, NOT a real spend ceiling. The real backstop is the
// monthly budget set in console.mistral.ai/billing.
const _planRate = new Map(); // key: ip|date, value: count
const _planGlobalRate = new Map(); // key: date, value: count
const PLAN_DAILY_PER_IP = 5;     // soft cap — covers honest "Start over" exploration
const PLAN_DAILY_GLOBAL = 100;   // global runaway-guard; ~$3 max per Edge instance/day

function planRateLimitOk(ip) {
  const day = new Date().toISOString().slice(0, 10);
  const gn = _planGlobalRate.get(day) || 0;
  if (gn >= PLAN_DAILY_GLOBAL) return { ok: false, reason: 'global' };
  const key = `${ip}|${day}`;
  const n = _planRate.get(key) || 0;
  if (n >= PLAN_DAILY_PER_IP) return { ok: false, reason: 'ip' };
  _planRate.set(key, n + 1);
  _planGlobalRate.set(day, gn + 1);
  return { ok: true };
}

export default async function handler(req) {
  if (req.method === 'GET') {
    const today = new Date().toISOString().slice(0, 10);
    return new Response(JSON.stringify({
      ok: true,
      message: 'Adapt plan generator. POST inputs here.',
      model: PLAN_MODEL,
      hasKey: !!process.env.MISTRAL_API_KEY,
      caps: {
        perIPDaily: PLAN_DAILY_PER_IP,
        globalDaily: PLAN_DAILY_GLOBAL,
        usedTodayThisInstance: _planGlobalRate.get(today) || 0,
        note: 'In-memory cap — resets on Edge cold start. Real backstop: Mistral console budget limit.',
      },
    }), { status: 200, headers: { 'Content-Type': 'application/json' } });
  }
  if (req.method !== 'POST') {
    return jsonErr(405, 'Method not allowed');
  }
  const apiKey = process.env.MISTRAL_API_KEY;
  if (!apiKey) return jsonErr(500, 'Server misconfigured: MISTRAL_API_KEY env var missing.');

  // Cost guard: cap how often any one IP can run plan generation (the most
  // expensive call in the app). Over the limit -> 429 with a clear message
  // so the frontend knows to fall back to the rule engine.
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'anon';
  const rl = planRateLimitOk(ip);
  if (!rl.ok) {
    const msg = rl.reason === 'global'
      ? 'Plan-generation daily limit reached for this server. Try again tomorrow or use the rule-engine plan.'
      : `Plan-generation daily limit reached for your IP (${PLAN_DAILY_PER_IP}/day). Resets at midnight UTC.`;
    return jsonErr(429, msg);
  }

  let body;
  try { body = await req.json(); } catch (e) { return jsonErr(400, 'Invalid JSON body'); }

  const inputs = body || {};
  const event = String(inputs.event || 'Half Ironman');
  const hours = Math.max(2, Math.min(20, Number(inputs.hours) || 5));
  const days = Array.isArray(inputs.days) && inputs.days.length > 0 ? inputs.days : ['Wed','Sat','Sun'];
  const raceDate = inputs.raceDate || '';
  const todayStr = inputs.today || new Date().toISOString().slice(0, 10);
  const profile = inputs.profile || {};
  const courseIntel = inputs.courseIntel || {};
  const location = inputs.location || '';

  // Compute weeks-to-race so we can pick a credible block layout.
  const weeksToRace = computeWeeksToRace(todayStr, raceDate);

  const systemPrompt = buildPlanSystemPrompt({ event, hours, days, weeksToRace, profile, courseIntel, location, todayStr });
  const userMsg = buildUserPrompt({ event, hours, days, raceDate, weeksToRace, profile, courseIntel, location });

  // Force a JSON-shaped response. Mistral supports response_format = {type:'json_object'}.
  const payload = {
    model: PLAN_MODEL,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMsg },
    ],
    response_format: { type: 'json_object' },
    max_tokens: MAX_TOKENS,
    temperature: 0.3, // low temp for consistency, but not 0 — we want some judgment
  };

  let upstream;
  try {
    upstream = await withTimeout(fetch(MISTRAL_URL, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    }), REQUEST_TIMEOUT_MS);
  } catch (e) {
    return jsonErr(502, 'Mistral request failed: ' + (e && e.message || 'unknown error'));
  }

  if (!upstream.ok) {
    let detail = '';
    try { detail = await upstream.text(); } catch (_) {}
    return jsonErr(upstream.status, `Mistral ${upstream.status}: ${String(detail).slice(0, 200)}`);
  }

  let response;
  try {
    response = await upstream.json();
  } catch (e) {
    return jsonErr(502, 'Mistral returned non-JSON');
  }

  const rawText = response?.choices?.[0]?.message?.content || '';
  if (!rawText) return jsonErr(502, 'Mistral returned empty content');

  let parsed;
  try { parsed = JSON.parse(rawText); }
  catch (e) {
    return jsonErr(502, 'Plan JSON parse failed: ' + (e && e.message || ''));
  }

  // Validate + normalize. If validation fails, return the failure to the
  // caller — the frontend can fall back to its rule engine.
  const validation = validatePlan(parsed, { event, hours, days, weeksToRace });
  if (!validation.ok) {
    return new Response(JSON.stringify({
      ok: false,
      error: 'Plan validation failed: ' + validation.reason,
      raw: parsed,
    }), { status: 422, headers: { 'Content-Type': 'application/json' } });
  }

  return new Response(JSON.stringify({ ok: true, plan: validation.plan, model: PLAN_MODEL }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
}

// ─── Prompt construction ──────────────────────────────────────────────────

function buildPlanSystemPrompt({ event, hours, days, weeksToRace, profile, courseIntel, location, todayStr }) {
  const isTri = /Ironman|Triathlon/i.test(event);
  const isRun = /Marathon|10K|5K/i.test(event);
  const disciplineNote = isTri
    ? 'Triathlon: balance swim, bike, run. The bike is the longest leg in distance terms; protect it. Run-off-bike is the most race-specific quality. Swim volume is hardest to keep up with low hours but maintain at least 1x/week.'
    : isRun
    ? 'Running event: long run is the keystone. Quality day = intervals or tempo. Easy days fill aerobic volume.'
    : 'General fitness — variety matters more than specificity. Mix run + bike + strength. No race taper.';

  return `You are Adapt's training plan engine. You build periodized endurance training plans grounded in established sport science. You output ONLY valid JSON conforming to the schema described below — no prose, no markdown, no comments.

═══ METHODOLOGICAL FOUNDATION ═══

Your plans MUST reflect these established frameworks:

1. **Joe Friel periodization (The Triathlete's / Cyclist's / Runner's Training Bible).** Block structure for endurance plans:
   - **Prep** (1-2 wks): general fitness, low-intensity, get into routine.
   - **Base 1-3** (4-12 wks total): aerobic-base building. Force/strength sessions allowed. Threshold work begins late.
   - **Build 1-2** (4-8 wks): race-specific intensity. Threshold + VO2 + race-pace work. Long sessions peak here.
   - **Peak** (1-2 wks): sharpening. High intensity, reduced volume.
   - **Race week / Taper** (1-3 wks depending on event): volume drops 40-60%, intensity maintained briefly then tapered.
   Adapt block lengths to the user's actual weeks-to-race. If weeks-to-race is short (<8), compress: Base 2-3, Build 2-3, Peak 1, Taper 1-2. Never skip a taper.

2. **Stephen Seiler polarized 80/20.** ~80% of session TIME (not session count) at low intensity (Z1-Z2, conversational), ~20% at high intensity (Z4+). Threshold/sweet-spot (Z3) is used SPARINGLY because it adds fatigue without proportional benefit. With low weekly hours (<5), the ratio shifts toward 75/25 — more concentrated quality is needed because total stimulus is limited. With high hours (>10), can be 85/15.

3. **Jack Daniels VDOT (Daniels' Running Formula).** Run intensities are anchored to the user's VDOT (a fitness number derivable from a recent race). Pace zones:
   - **E** (Easy / Z2): conversational, 65-79% HRmax
   - **M** (Marathon pace): goal marathon effort
   - **T** (Threshold): comfortably hard, 1-hr race pace, 88-92% HRmax. Cruise intervals 5-15 min.
   - **I** (Interval): VO2max work, 3-5 min reps at 95-100% HRmax with equal recovery
   - **R** (Repetition): neuromuscular, 30s-2min very fast with full recovery
   When the user hasn't given you a VDOT or recent race time, prescribe by RPE and HR-zone instead, and explicitly say "estimate your zones from a 5K time trial in week 2."

4. **Discipline-specific intensity:**
   - Swim: CSS pace (Critical Swim Speed) for threshold sets; technique drills mid-set; aerobic continuous swims 30-60 min for base.
   - Bike: zones from FTP. Sweet spot (88-94% FTP) used in Base; Threshold (95-105%) in Build; VO2max (106-120%) in Peak.
   - Run: Daniels above.
   - Brick: bike-then-run, run leg = 15-30% of bike duration in Base, growing to 30-50% in Peak.

5. **Long-session progression within a phase.** Long-session duration ramps week-over-week within a block (e.g. Base: 60→75→90→back-off-60), then a deload, then continues building in next block.

6. **Recovery + deload.** Every 3rd or 4th week MUST be a back-off week (volume cut ~25%, intensity preserved). High weekly hours = more frequent deload (every 3 weeks); low hours = every 4 weeks.

7. **Race-specific taper.**
   - 5K/10K: 7-day taper, -30% volume.
   - Half Marathon: 10-14 day taper, -30% to -40%.
   - Marathon: 14-21 day taper, -40% to -50%.
   - Sprint Tri / Olympic Tri: 7-10 day taper, -30%.
   - Half Ironman: 14 day taper, -45%.
   - Full Ironman: 21 day taper, -50% week 1, -65% week 2, race week ~25% with race-pace primers.

═══ HARD CONSTRAINTS — MUST follow ═══

• Use ONLY the user's selected training days for sessions. Other days = full rest. Do not invent training days.
• Total weekly minutes must be within ±15% of the user's stated weekly hours × 60. (User said ${hours} hrs/week → target ~${Math.round(hours * 60)} min/week.)
• Each week must have at least one full rest day (duration:0, type:'rest'). Two if hours <= 4.
• Quality (high-intensity) sessions must be spaced at least 48 hours apart, ideally 72.
• No week-over-week total-hours jump exceeds +25% or drops more than 35% (deload/taper aside).
• Long session is on Sat or Sun if those are training days; otherwise on the last selected day.
• Every session has: name, type (run/bike/swim/strength/brick/mobility/rest/quality), durationMin (integer), intensity ('Z2','Z3','Z4','Z5','mixed','rest'), prescription (1-2 sentence description of the workout structure), targets (HR/pace/RPE guidance — use ranges and reference the appropriate Daniels/CTL anchor when applicable).
• prescription MUST reference specific zones, drills, or intervals — not just "easy aerobic." E.g. "8x400m at I pace (~5K race pace) with 400m recoveries; 1mi WU + CD" not "intervals."

═══ DISCIPLINE NOTES FOR THIS USER ═══

Event: ${event}
${disciplineNote}
Weeks to race: ${weeksToRace || 'not provided — assume 16'}
Weekly hours: ${hours}
Training days: ${days.join(', ')}
Today: ${todayStr}
${location ? 'Race location: ' + location : ''}
${courseIntel && courseIntel.terrain ? 'Course terrain: ' + courseIntel.terrain : ''}
${courseIntel && courseIntel.climate ? 'Course climate: ' + courseIntel.climate : ''}
${profile && profile.exp ? 'Experience: ' + profile.exp : ''}
${profile && profile.injury ? 'Injury status: ' + profile.injury : ''}
${profile && profile.sleep ? 'Typical sleep: ' + profile.sleep : ''}

═══ OUTPUT JSON SCHEMA — STRICT ═══

You MUST output an object exactly matching this shape:

{
  "summary": "1-2 sentence top-line: what the plan optimizes for, the methodology you applied",
  "blocks": [
    { "name": "Base 1", "weeks": [0,1,2], "focus": "aerobic base + neuromuscular form" },
    ...
  ],
  "weeks": [
    {
      "weekIndex": 0,
      "label": "Week 1 — Base 1",
      "phase": "Base",
      "weeklyTotalMin": 300,
      "intensityRatio": "82/18",
      "focus": "establish aerobic base, get into rhythm",
      "deload": false,
      "sessions": {
        "Mon": { "name": "Rest", "type": "rest", "durationMin": 0, "intensity": "rest", "prescription": "Full rest. Walk 20 min if you want.", "targets": "" },
        "Tue": { "name": "...", ... },
        ...
        "Sun": { ... }
      }
    },
    ... (one per week, weekIndex 0 through weeksToRace-1)
  ],
  "notesForUser": [
    "1-3 short bullet notes about the plan's logic that the user should know"
  ]
}

NO prose outside this JSON. NO markdown. NO trailing comments. Just the object.`;
}

function buildUserPrompt({ event, hours, days, raceDate, weeksToRace, profile, courseIntel, location }) {
  return `Generate a complete periodized training plan for me.

Inputs:
- Event: ${event}
- Race date: ${raceDate || 'not set'}
- Weeks to race: ${weeksToRace}
- Weekly hours available: ${hours}
- Training days: ${days.join(', ')}
- Location: ${location || 'unspecified'}
${courseIntel && courseIntel.terrain ? '- Course terrain: ' + courseIntel.terrain : ''}
${courseIntel && courseIntel.climate ? '- Course climate: ' + courseIntel.climate : ''}
${profile && profile.exp ? '- Experience level: ' + profile.exp : ''}
${profile && profile.freq ? '- Recent training frequency: ' + profile.freq : ''}
${profile && profile.injury ? '- Injury status: ' + profile.injury : ''}
${profile && profile.sleep ? '- Sleep: ' + profile.sleep : ''}

Build the full ${Math.min(weeksToRace || 16, 24)}-week (or fewer if less time) plan now. Output the JSON only.`;
}

// ─── Plan validation ─────────────────────────────────────────────────────

const VALID_TYPES = ['run','bike','swim','strength','brick','mobility','rest','quality'];
const DAYS_ORDER = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];

function validatePlan(parsed, { event, hours, days, weeksToRace }) {
  if (!parsed || typeof parsed !== 'object') return { ok: false, reason: 'plan is not an object' };
  if (typeof parsed.summary !== 'string') return { ok: false, reason: 'missing summary' };
  if (!Array.isArray(parsed.weeks) || parsed.weeks.length === 0) return { ok: false, reason: 'missing weeks array' };
  if (parsed.weeks.length > 30) return { ok: false, reason: 'plan too long (>30 weeks)' };

  const targetWeeklyMin = hours * 60;
  const minWeeklyMin = Math.round(targetWeeklyMin * 0.30);   // hard floor; deload/taper ok
  const maxWeeklyMin = Math.round(targetWeeklyMin * 1.30);   // hard ceiling
  const trainingDaySet = new Set(days);

  let prevWeekMin = null;
  for (let wi = 0; wi < parsed.weeks.length; wi++) {
    const wk = parsed.weeks[wi];
    if (!wk || typeof wk !== 'object') return { ok: false, reason: `week ${wi} is not an object` };
    if (!wk.sessions || typeof wk.sessions !== 'object') return { ok: false, reason: `week ${wi} missing sessions` };
    let weekMin = 0;
    let restCount = 0;
    let qualityDays = [];
    for (const dayName of DAYS_ORDER) {
      const sess = wk.sessions[dayName];
      if (!sess) return { ok: false, reason: `week ${wi} ${dayName} missing` };
      if (typeof sess.name !== 'string') sess.name = sess.name || 'Untitled';
      if (typeof sess.durationMin !== 'number') sess.durationMin = 0;
      if (sess.durationMin < 0) sess.durationMin = 0;
      if (sess.durationMin > 360) return { ok: false, reason: `week ${wi} ${dayName} duration > 6h` };
      if (!VALID_TYPES.includes(sess.type)) sess.type = sess.durationMin === 0 ? 'rest' : 'run';
      if (!sess.intensity) sess.intensity = sess.type === 'rest' ? 'rest' : 'Z2';
      if (typeof sess.prescription !== 'string') sess.prescription = '';
      if (typeof sess.targets !== 'string') sess.targets = sess.targets ? String(sess.targets) : '';
      // Non-training day enforcement — if user didn't pick this day, force it to rest.
      if (!trainingDaySet.has(dayName) && sess.durationMin > 0) {
        sess.durationMin = 0;
        sess.type = 'rest';
        sess.name = 'Rest';
        sess.intensity = 'rest';
        sess.prescription = 'Full rest day.';
        sess.targets = '';
      }
      weekMin += sess.durationMin;
      if (sess.type === 'rest' || sess.durationMin === 0) restCount++;
      if (sess.type === 'quality' || sess.type === 'brick' || (sess.intensity && /Z[345]/.test(sess.intensity))) {
        qualityDays.push(DAYS_ORDER.indexOf(dayName));
      }
    }
    if (restCount === 0) return { ok: false, reason: `week ${wi} has zero rest days` };
    // Quality spacing: any two quality days within 1 day of each other = rejection.
    for (let i = 1; i < qualityDays.length; i++) {
      if (qualityDays[i] - qualityDays[i - 1] === 1) {
        return { ok: false, reason: `week ${wi} has back-to-back quality days` };
      }
    }
    // Weekly volume sanity. Allow taper weeks below floor; flag if >ceiling.
    if (weekMin > maxWeeklyMin) return { ok: false, reason: `week ${wi} total ${weekMin}min exceeds ceiling ${maxWeeklyMin}` };
    // Week-over-week jump check (skip first week).
    if (prevWeekMin != null && weekMin > 0) {
      const ratio = weekMin / prevWeekMin;
      if (ratio > 1.30) return { ok: false, reason: `week ${wi} jumped ${Math.round((ratio - 1) * 100)}% over previous week` };
    }
    if (typeof wk.weeklyTotalMin !== 'number') wk.weeklyTotalMin = weekMin;
    prevWeekMin = weekMin;
  }
  return { ok: true, plan: parsed };
}

// ─── Helpers ──────────────────────────────────────────────────────────────

function jsonErr(status, message) {
  return new Response(JSON.stringify({ ok: false, error: message }), {
    status, headers: { 'Content-Type': 'application/json' },
  });
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error('timeout after ' + ms + 'ms')), ms);
    promise.then(v => { clearTimeout(t); resolve(v); }, e => { clearTimeout(t); reject(e); });
  });
}

function computeWeeksToRace(todayStr, raceDateStr) {
  if (!raceDateStr) return null;
  try {
    const today = new Date(todayStr + 'T00:00:00Z');
    const race = new Date(raceDateStr + 'T00:00:00Z');
    if (isNaN(race.getTime()) || isNaN(today.getTime())) return null;
    const days = Math.round((race - today) / (24 * 60 * 60 * 1000));
    if (days <= 0) return 0;
    return Math.max(1, Math.ceil(days / 7));
  } catch (e) { return null; }
}
