// Adapt — AI-generated training plan endpoint
//
// POST a user's onboarding inputs; get back a structured periodized plan
// generated by Mistral Large with heavy methodology priming (Friel block
// periodization, Daniels VDOT pacing, Seiler 80/20 polarized intensity,
// race-specific tapers, discipline-specific session vocabulary).
//
// Returns deterministic JSON the frontend can render. Validates the AI's
// output against safety guardrails (sane hours, no zero rest weeks, no
// week-over-week jumps > 30%, at least one rest day per week). On any
// failure (malformed JSON, validation reject, network error) the frontend
// falls back to the rule-based generator so users always get *something*.

export const config = { runtime: 'edge' };

const MISTRAL_URL = 'https://api.mistral.ai/v1/chat/completions';
const PLAN_MODEL = 'mistral-large-latest'; // quality > speed for plan generation
const MAX_TOKENS = 4500;                    // 6 weeks of detail fits in ~3000-4000 tokens
const REQUEST_TIMEOUT_MS = 45000;

// Plan generation is the most expensive call in this app (~$0.025-0.04 per
// invocation with Mistral Large). Cap per-IP attempts hard. The map is
// in-memory and Edge functions are stateless across instances/cold starts —
// this is best-effort, NOT a real spend ceiling. The real backstop is the
// monthly budget set in console.mistral.ai/billing.
const _planRate = new Map(); // key: ip|date, value: count
const _planGlobalRate = new Map(); // key: date, value: count
const PLAN_DAILY_PER_IP = 5;     // soft cap — covers honest "Start over" exploration
const PLAN_DAILY_GLOBAL = 100;   // global runaway-guard; ~$3 max per Edge instance/day

function planRateLimitOk(ip) {
  const day = new Date().toISOString().slice(0, 10);
  const gn = _planGlobalRate.get(day) || 0;
  if (gn >= PLAN_DAILY_GLOBAL) return { ok: false, reason: 'global' };
  const key = `${ip}|${day}`;
  const n = _planRate.get(key) || 0;
  if (n >= PLAN_DAILY_PER_IP) return { ok: false, reason: 'ip' };
  _planRate.set(key, n + 1);
  _planGlobalRate.set(day, gn + 1);
  return { ok: true };
}

export default async function handler(req) {
  if (req.method === 'GET') {
    const today = new Date().toISOString().slice(0, 10);
    return new Response(JSON.stringify({
      ok: true,
      message: 'Adapt plan generator. POST inputs here.',
      model: PLAN_MODEL,
      hasKey: !!process.env.MISTRAL_API_KEY,
      caps: {
        perIPDaily: PLAN_DAILY_PER_IP,
        globalDaily: PLAN_DAILY_GLOBAL,
        usedTodayThisInstance: _planGlobalRate.get(today) || 0,
        note: 'In-memory cap — resets on Edge cold start. Real backstop: Mistral console budget limit.',
      },
    }), { status: 200, headers: { 'Content-Type': 'application/json' } });
  }
  if (req.method !== 'POST') {
    return jsonErr(405, 'Method not allowed');
  }
  const apiKey = process.env.MISTRAL_API_KEY;
  if (!apiKey) return jsonErr(500, 'Server misconfigured: MISTRAL_API_KEY env var missing.');

  // Cost guard: cap how often any one IP can run plan generation (the most
  // expensive call in the app). Over the limit -> 429 with a clear message
  // so the frontend knows to fall back to the rule engine.
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'anon';
  const rl = planRateLimitOk(ip);
  if (!rl.ok) {
    const msg = rl.reason === 'global'
      ? 'Plan-generation daily limit reached for this server. Try again tomorrow or use the rule-engine plan.'
      : `Plan-generation daily limit reached for your IP (${PLAN_DAILY_PER_IP}/day). Resets at midnight UTC.`;
    return jsonErr(429, msg);
  }

  let body;
  try { body = await req.json(); } catch (e) { return jsonErr(400, 'Invalid JSON body'); }

  const inputs = body || {};
  const event = String(inputs.event || 'Half Ironman');
  const hours = Math.max(2, Math.min(20, Number(inputs.hours) || 5));
  const days = Array.isArray(inputs.days) && inputs.days.length > 0 ? inputs.days : ['Wed','Sat','Sun'];
  const raceDate = inputs.raceDate || '';
  const todayStr = inputs.today || new Date().toISOString().slice(0, 10);
  const profile = inputs.profile || {};
  const courseIntel = inputs.courseIntel || {};
  const triFocus = inputs.triFocus || {};
  const fitnessMarkers = inputs.fitnessMarkers || {};
  const availableDisciplines = Array.isArray(inputs.availableDisciplines) ? inputs.availableDisciplines : [];
  const difficultyAdjust = inputs.difficultyAdjust || null;
  const location = inputs.location || '';

  // Compute weeks-to-race so we can pick a credible block layout.
  const weeksToRace = computeWeeksToRace(todayStr, raceDate);

  const systemPrompt = buildPlanSystemPrompt({ event, hours, days, weeksToRace, profile, courseIntel, triFocus, fitnessMarkers, availableDisciplines, difficultyAdjust, location, todayStr });
  const userMsg = buildUserPrompt({ event, hours, days, raceDate, weeksToRace, profile, courseIntel, triFocus, fitnessMarkers, availableDisciplines, difficultyAdjust, location });

  // Force a JSON-shaped response. Mistral supports response_format = {type:'json_object'}.
  const payload = {
    model: PLAN_MODEL,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMsg },
    ],
    response_format: { type: 'json_object' },
    max_tokens: MAX_TOKENS,
    temperature: 0.3, // low temp for consistency, but not 0 — we want some judgment
  };

  let upstream;
  try {
    upstream = await withTimeout(fetch(MISTRAL_URL, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    }), REQUEST_TIMEOUT_MS);
  } catch (e) {
    return jsonErr(502, 'Mistral request failed: ' + (e && e.message || 'unknown error'));
  }

  if (!upstream.ok) {
    let detail = '';
    try { detail = await upstream.text(); } catch (_) {}
    return jsonErr(upstream.status, `Mistral ${upstream.status}: ${String(detail).slice(0, 200)}`);
  }

  let response;
  try {
    response = await upstream.json();
  } catch (e) {
    return jsonErr(502, 'Mistral returned non-JSON');
  }

  const rawText = response?.choices?.[0]?.message?.content || '';
  if (!rawText) return jsonErr(502, 'Mistral returned empty content');

  let parsed;
  try { parsed = JSON.parse(rawText); }
  catch (e) {
    return jsonErr(502, 'Plan JSON parse failed: ' + (e && e.message || ''));
  }

  // Validate + normalize. If validation fails, return the failure to the
  // caller — the frontend can fall back to its rule engine.
  const validation = validatePlan(parsed, { event, hours, days, weeksToRace });
  if (!validation.ok) {
    return new Response(JSON.stringify({
      ok: false,
      error: 'Plan validation failed: ' + validation.reason,
      raw: parsed,
    }), { status: 422, headers: { 'Content-Type': 'application/json' } });
  }

  return new Response(JSON.stringify({ ok: true, plan: validation.plan, model: PLAN_MODEL }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
}

// ─── Prompt construction ──────────────────────────────────────────────────

// Render the user's calibrated fitness markers as a prompt block. Empty
// string when nothing is set — the AI falls back to estimated zones.
function buildFitnessMarkersBlock(m) {
  if (!m || typeof m !== 'object') return '';
  const lines = [];
  if (m.runRace && m.runRace.distance && m.runRace.time) {
    lines.push(`• Recent run race: ${m.runRace.distance} in ${m.runRace.time}${m.runRace.when ? ' (' + m.runRace.when + ')' : ''}`);
    lines.push('  → Derive Daniels VDOT from this. Use it to prescribe specific run paces (E / M / T / I / R) in every run session\'s targets.');
  }
  if (m.maxHr) {
    lines.push(`• Max HR: ${m.maxHr} bpm`);
    lines.push(`  → HR zones from this: Z1 ${Math.round(m.maxHr*0.60)}-${Math.round(m.maxHr*0.70)}, Z2 ${Math.round(m.maxHr*0.70)}-${Math.round(m.maxHr*0.80)}, Z3 ${Math.round(m.maxHr*0.80)}-${Math.round(m.maxHr*0.87)}, Z4 ${Math.round(m.maxHr*0.87)}-${Math.round(m.maxHr*0.93)}, Z5 ${Math.round(m.maxHr*0.93)}-${m.maxHr}.`);
  }
  if (m.restingHr) {
    lines.push(`• Resting HR: ${m.restingHr} bpm`);
    lines.push('  → Use as a baseline. Coach Chat compares morning HR readings against this.');
  }
  if (m.ftp) {
    const f = m.ftp;
    lines.push(`• Bike FTP: ${f}W`);
    lines.push(`  → Zones: Z2 ${Math.round(f*0.55)}-${Math.round(f*0.75)}W, Sweet Spot ${Math.round(f*0.88)}-${Math.round(f*0.94)}W, Threshold ${Math.round(f*0.95)}-${Math.round(f*1.05)}W, VO2max ${Math.round(f*1.06)}-${Math.round(f*1.20)}W. Use these specific watts in every bike session's targets.`);
  }
  if (m.css) {
    lines.push(`• Swim CSS: ${m.css} per 100m`);
    lines.push('  → Easy: CSS + 8-10s/100m. Threshold sets: at CSS. Fast: CSS - 3s/100m. Use these specific paces in every swim session\'s targets.');
  }
  if (m.runAbility) {
    const map = {
      'walk-run': 'Just walking + short jogs (<5 min continuous). Use Couch-to-5K-style walk/run intervals; do NOT prescribe continuous runs.',
      'under-15': 'Up to 15 min continuous. Mix of walk-run and short continuous easy runs; cap long sessions at ~25 min.',
      '15-30': '15-30 min continuous. Easy aerobic 20-30 min; build long runs gradually toward 35-40 min.',
      '30-60': '30-60 min continuous. Standard easy aerobic + long runs scale normally.',
      '60-plus': '60+ min continuous. Long-run progressions can reach race-specific durations.',
    };
    lines.push(`• Current run ability: ${map[m.runAbility] || m.runAbility}`);
  }
  if (lines.length === 0) return '';
  return `\n\n═══ CALIBRATED FITNESS MARKERS — USE THESE EXACT NUMBERS ═══\n\n${lines.join('\n')}\n\nWhen prescribing sessions, USE THESE NUMBERS. Don't write "Z2" — write the actual HR range "${m.maxHr ? Math.round(m.maxHr*0.70) + '-' + Math.round(m.maxHr*0.80) + ' bpm' : 'their HR Z2 range'}". Don't write "threshold pace" — derive it from VDOT and write "~7:15/mi" or whatever's correct. The user gave us real data; reflect that in every prescription and target line.`;
}

function buildPlanSystemPrompt({ event, hours, days, weeksToRace, profile, courseIntel, triFocus, fitnessMarkers, availableDisciplines, difficultyAdjust, location, todayStr }) {
  const isTri = /Ironman|Triathlon/i.test(event);
  const isMarathon = /Marathon/i.test(event) && !/Half/i.test(event);
  const isHalfMar = /Half Marathon/i.test(event);
  const isShortRun = /\b(5K|10K)\b/i.test(event);
  const isRun = isMarathon || isHalfMar || isShortRun;
  const isGeneral = /General fitness/i.test(event);
  const limiter = (triFocus && triFocus.limiter) || 'balanced';
  const strategy = (triFocus && triFocus.strategy) || 'balanced';

  const hasStrength = Array.isArray(availableDisciplines) && availableDisciplines.includes('strength');
  const hasSwim = Array.isArray(availableDisciplines) && availableDisciplines.includes('swim');
  const hasBike = Array.isArray(availableDisciplines) && availableDisciplines.includes('bike');
  const hasTrainer = Array.isArray(availableDisciplines) && availableDisciplines.includes('trainer');

  // Build a discipline-allocation note that the plan engine MUST respect.
  let disciplineNote;
  if (isTri) {
    if (strategy === 'focus' && limiter !== 'balanced') {
      const allocation = (() => {
        if (limiter === 'swim') return 'swim 35% / bike 35% / run 30% (heavy on swim — the user said this is their weakness)';
        if (limiter === 'bike') return 'swim 15% / bike 55% / run 30% (heavy on bike — the user said this is their weakness)';
        if (limiter === 'run')  return 'swim 15% / bike 35% / run 50% (heavy on run — the user said this is their weakness)';
        return 'swim 20% / bike 45% / run 35% (default tri allocation)';
      })();
      disciplineNote = `Triathlon, weakness-focused build. The user identified ${limiter.toUpperCase()} as their LIMITER and chose a FOCUS strategy. Allocate weekly time roughly ${allocation}. ` +
        `This means: in every week, the prescribed minutes for ${limiter} sessions should be the largest discipline bucket. ` +
        `Add an extra ${limiter} session if the day count allows. ` +
        `Quality day prescription should target ${limiter}-specific intensity (${limiter==='swim' ? 'CSS sets, technique work' : limiter==='bike' ? 'sweet spot / threshold intervals' : 'I-pace / threshold intervals'}). ` +
        `Long session: if it would normally be a brick, weight the ${limiter} portion ~60% of total session time. ` +
        `Race-specificity DOES NOT override this — the user knows their gap and is paying for the focus.`;
    } else if (strategy === 'maintain' && limiter !== 'balanced') {
      disciplineNote = `Triathlon, maintenance mode for ${limiter.toUpperCase()}. Hold ${limiter} volume steady (~1 session/wk minimum, technique-focused) while building the other two disciplines toward race specificity.`;
    } else {
      disciplineNote = 'Triathlon: balance swim, bike, run. The bike is the longest leg in distance terms; protect it. Run-off-bike is the most race-specific quality. Swim volume is hardest to keep up with low hours but maintain at least 1x/week.';
    }
    if (!hasSwim) disciplineNote += '\n⚠ User has no swim access — replace prescribed swim sessions with bike trainer or strength. Note this clearly in session notes.';
    if (!hasBike && !hasTrainer) disciplineNote += '\n⚠ User has no bike/trainer access — bike sessions get replaced with run cross-training. Note clearly.';
  } else if (isMarathon) {
    disciplineNote = `Marathon training. The LONG RUN is THE keystone session — everything else exists to protect and build it.

Weekly structure (typical):
• Long run — progressive, builds from current ability toward race distance × 80% (~21 mi peak, 3-4 weeks pre-race). Add ≤10% per week. Deload week (cut 25-30%) every 4 weeks.
• Quality (1×/wk in Build, 2×/wk in Peak): tempo runs (T-pace, 20-40 min cruise intervals), marathon-pace blocks (M-pace, 6-12 mi within long run), hill repeats early, V̇O2 intervals occasionally.
• Easy aerobic — 60-80% of weekly volume at conversational Z2.
• Race-pace work in Build/Peak: include marathon-pace segments INSIDE the long run (e.g., last 60 min at goal pace) — the most specific session in marathon training.

Pace anchor: derive everything from VDOT (from user's recent race time when present).`;
  } else if (isHalfMar) {
    disciplineNote = `Half marathon training. Mix of aerobic base and threshold work — the half is fundamentally a threshold race.

Weekly structure (typical):
• Long run — builds toward race distance × 80% (~10-11 mi peak). Slightly shorter than marathon long-runs but still the keystone.
• Threshold session — T-pace cruise intervals (5-15 min reps with 1-3 min jog recovery), or steady tempo runs (20-40 min at threshold). 1×/wk minimum in Build.
• Easy aerobic — fills volume.
• Race-pace work in Peak: half-marathon-pace blocks within the long run (e.g., 5 mi at goal pace).

Pace anchor: T-pace (threshold) is the most important number for HM athletes.`;
  } else if (isShortRun) {
    const expLevel = profile && profile.exp;
    const runAbility = fitnessMarkers && fitnessMarkers.runAbility;
    const isBeginner = expLevel === 'new' || runAbility === 'walk-run' || runAbility === 'under-15';
    if (isBeginner) {
      disciplineNote = `Short-distance run event (${event}) — BEGINNER PATH. The user's experience or current run ability is limited (exp=${expLevel || 'unknown'}, runAbility=${runAbility || 'unknown'}).

═══ CANONICAL REFERENCES — anchor the progression here ═══

Calibrate the build against established Couch-to-5K / Couch-to-10K programs. Do not invent your own progression — match these proven structures:

• NHS Couch to 5K (9 weeks, 3 sessions/wk): the gold standard. Week 1: 60s jog / 90s walk × 8. Week 5 day 3: 20 min continuous run. Week 9: 30 min continuous (~5K).
• Hal Higdon Novice 5K (8 weeks): blends walk/run with strength + cross-train days. Conservative for true beginners.
• Hal Higdon Novice 10K (12 weeks): for runners who already complete 5K. Adds a longer run and one quality day.
• Jeff Galloway Run-Walk-Run: a sustainable approach for everyone — even race finishers can use 4:1 run/walk ratios indefinitely.

Use these programs as templates. If the user's runAbility says they cannot run 10 min continuously, START where NHS C25K week 1 starts — not at "30 min easy run."

═══ ADJUSTMENT MECHANISM ═══

If the user has signaled difficulty preferences (context.difficultyAdjust):
• 'too-easy' / 'easier' (negative adjustment): The user explicitly said the previous plan was too easy. Step the progression up by 1 week — start where the previous plan was at week 2-3. Add quality earlier (week 3 instead of week 5).
• 'too-hard' / 'harder' (positive adjustment from user perspective is "make it easier"): Walk the progression back. Lengthen walk intervals, shorten run intervals.
Default: no adjustment, follow the canonical NHS C25K curve.

═══ HARD CAPS FOR BEGINNERS — DO NOT EXCEED ═══

These are not guidelines, they are LIMITS. The user said ${hours} hrs/week are "available" but DO NOT FILL THAT TIME. Filling time the user can't physically run is how new runners get injured. The plan should USE LESS TIME than they have available in early weeks.

• Maximum session duration: **30 min in weeks 1-2, 35 min in weeks 3-4, 40 min in weeks 5+**. NEVER go over even if the user has 5+ hrs/week available.
• Maximum sessions per week: **3 run sessions**. Even if user picked 5 days, the other 2 are rest, mobility, or strength (if available).
• Maximum total weekly RUN time: **week 1: 60-75 min**, **week 2: 75-85 min**, **week 3: 85-95 min**, **week 4: deload to 70 min**. Build ≤10%/week. NEVER exceed these caps in the first 6 weeks even if hrs/week says 4 or 5.
• If hrs/week × 60 > weekly run cap, fill the gap with REST or STRENGTH (if available) or MOBILITY — not more running.

═══ SESSION TEMPLATES (use these — don't invent something else) ═══

runAbility='walk-run' (walking + short jogs):
• Week 1 sessions: "5 min walk WU + 8×(60s jog / 90s walk) + 5 min walk CD ≈ 28 min"
• Week 2: "5 min walk + 8×(75s jog / 75s walk) + 5 min walk ≈ 30 min"
• Week 3: "5 min walk + 6×(2 min jog / 90s walk) + 5 min walk ≈ 31 min"
• Week 4 (deload): "5 min walk + 5×(2 min jog / 2 min walk) + 5 min walk ≈ 30 min"
• Week 5+: gradually extend jog / shorten walk toward 20-25 min continuous by week 8

runAbility='under-15' (can run up to 15 min continuous):
• Week 1: "5 min walk + 4×(3 min jog / 90s walk) + 5 min walk ≈ 28 min"
• Week 2: "5 min walk + 3×(5 min jog / 90s walk) + 5 min walk ≈ 30 min"
• Week 3: "5 min walk + 15-18 min easy continuous + 3 min walk ≈ 25 min"
• Week 4+: build continuous 20-30 min toward race week

runAbility='15-30':
• Week 1: 20-25 min continuous easy with one optional walk break.
• Build to 30-35 min by week 3-4.

═══ ABSOLUTELY DO NOT PRESCRIBE ═══

• Threshold or interval work in weeks 1-4 (joints/tendons need adaptation)
• Continuous runs > user's current capacity × 1.25
• Sessions over 45 min — even long runs — for a beginner training for a 5K
• Brick sessions (this is not a triathlon)
• Bike or swim sessions (this is a run event)
• "Quality" type sessions until week 5+

═══ DO PRESCRIBE ═══

• Strides (4-6×20s fast feel + full walk recovery) starting week 3
• Strength sessions if available (huge injury-protection win)
• 2-3 run days/wk max; remaining days = rest, mobility, or strength

The plan is "build the runner first, sharpen second." Patience over volume.`;
    } else {
      disciplineNote = `Short-distance run event (${event}). Speed and V̇O2max dominate — long aerobic capacity is the FLOOR, not the ceiling.

Weekly structure (typical):
• Long run — capped at 60-75 min progressive Z2-Z3 (this isn't a marathon).
• Quality — at least 1×/wk in Build; intervals at I-pace (V̇O2max, 3-5 min reps with equal recovery) or repetitions at R-pace (30s-2min very fast with full recovery). Hill repeats are excellent for both speed AND strength.
• Easy aerobic — supports recovery between hard sessions.
• Race-pace work in Peak: short reps at goal 5K/10K pace.

Pace anchor: I-pace and R-pace (Daniels), derived from VDOT.`;
    }
  } else if (isGeneral) {
    disciplineNote = `General fitness — no race target. Goal is consistency + variety + injury-free year-round training.

Weekly structure:
• Mix run + bike (or trainer) + ${hasStrength ? 'strength' : 'mobility'} on rotating days.
• 80/20 polarized still applies — most sessions easy, ~20% time at quality.
• No taper. No peaks. Build a 4-week microcycle (3 build + 1 deload at -25%) and repeat.
• Allow holiday/vacation flexibility — the goal is showing up consistently, not hitting peaks.
• Each session has clear intent (aerobic / quality / strength / recovery), not "go run for 45 min".`;
  } else {
    disciplineNote = `Event: ${event}. Apply standard endurance principles: long-effort keystone, 1-2 quality sessions per week, easy aerobic volume, deload every 3-4 weeks.`;
  }

  // Strength integration. Endurance research consistently shows 1-2 strength
  // sessions per week reduces injury risk + improves running economy/power.
  // Only prescribe when the user has access; never force.
  let strengthNote = '';
  if (hasStrength) {
    strengthNote = `

═══ STRENGTH SESSIONS — USER HAS ACCESS, USE THEM ═══

The user indicated they have strength/gym access. Prescribe 1-2 strength sessions per week per Friel/Lydiard guidance. NEVER skip strength entirely just because the focus is endurance — research is clear: 1-2x/wk strength reduces injury risk by 30-50% and improves running economy 4-8%.

Phase-specific prescriptions (use in session.prescription field — be SPECIFIC, not generic):

• PREP / BASE 1: foundational strength. Compound movements 3×8-12. Example prescription: "Goblet squats 3×10 @ moderate, single-leg deadlift 3×8/side, push-ups 3×10, plank 3×45s, hip bridges 3×12. 60-75s rest between sets. Form > weight."

• BASE 2-3: max strength. Heavier load, lower reps. Example: "Back squat 4×5 @ 80% 1RM, deadlift 3×5, bench/press 3×6, pull-ups 3×6, plank variations 3×45s. 2-3 min rest. Move slowly under load."

• BUILD 1-2: strength endurance + power. Lighter load, plyometrics. Example: "Box jumps 4×5, squats 3×8 @ 70%, single-leg RDL 3×10/side, push-ups 3×AMRAP, lateral lunges 3×10/side, core circuit. 60-90s rest."

• PEAK: maintenance only. Every 5-7 days. Example: "Squats 3×6 @ moderate, RDL 3×6, push 3×6, pull 3×6, core 3×30s plank. Quick + sharp, no failure."

• TAPER (race week and the week before): drop strength entirely. The legs need to be fresh.

Place strength sessions:
• Same day as a quality session (ideally afternoon, with quality in the morning)
• Or on an "easy" day (after the easy aerobic session, not before)
• NEVER day before a long session
• NEVER day before/after race-pace work in build phase

For session type, use 'strength' in the session.type field. Duration: 30-50 min. Intensity: 'mixed' (it's neither cardio Z nor zoneless rest).`;
  } else {
    strengthNote = `\n\nNo strength access — do NOT prescribe strength sessions. If a user-typical week would include strength, replace with mobility (15-20 min stretching + dynamic) or skip.`;
  }
  disciplineNote += strengthNote;

  return `You are Adapt's training plan engine. You build periodized endurance training plans grounded in established sport science. You output ONLY valid JSON conforming to the schema described below — no prose, no markdown, no comments.

═══ METHODOLOGICAL FOUNDATION ═══

Your plans MUST reflect these established frameworks:

1. **Joe Friel periodization (The Triathlete's / Cyclist's / Runner's Training Bible).** Block structure for endurance plans:
   - **Prep** (1-2 wks): general fitness, low-intensity, get into routine.
   - **Base 1-3** (4-12 wks total): aerobic-base building. Force/strength sessions allowed. Threshold work begins late.
   - **Build 1-2** (4-8 wks): race-specific intensity. Threshold + VO2 + race-pace work. Long sessions peak here.
   - **Peak** (1-2 wks): sharpening. High intensity, reduced volume.
   - **Race week / Taper** (1-3 wks depending on event): volume drops 40-60%, intensity maintained briefly then tapered.
   Adapt block lengths to the user's actual weeks-to-race. If weeks-to-race is short (<8), compress: Base 2-3, Build 2-3, Peak 1, Taper 1-2. Never skip a taper.

2. **Stephen Seiler polarized 80/20.** ~80% of session TIME (not session count) at low intensity (Z1-Z2, conversational), ~20% at high intensity (Z4+). Threshold/sweet-spot (Z3) is used SPARINGLY because it adds fatigue without proportional benefit. With low weekly hours (<5), the ratio shifts toward 75/25 — more concentrated quality is needed because total stimulus is limited. With high hours (>10), can be 85/15.

3. **Jack Daniels VDOT (Daniels' Running Formula).** Run intensities are anchored to the user's VDOT (a fitness number derivable from a recent race). Pace zones:
   - **E** (Easy / Z2): conversational, 65-79% HRmax
   - **M** (Marathon pace): goal marathon effort
   - **T** (Threshold): comfortably hard, 1-hr race pace, 88-92% HRmax. Cruise intervals 5-15 min.
   - **I** (Interval): VO2max work, 3-5 min reps at 95-100% HRmax with equal recovery
   - **R** (Repetition): neuromuscular, 30s-2min very fast with full recovery
   When the user hasn't given you a VDOT or recent race time, prescribe by RPE and HR-zone instead, and explicitly say "estimate your zones from a 5K time trial in week 2."

4. **Discipline-specific intensity:**
   - Swim: CSS pace (Critical Swim Speed) for threshold sets; technique drills mid-set; aerobic continuous swims 30-60 min for base.
   - Bike: zones from FTP. Sweet spot (88-94% FTP) used in Base; Threshold (95-105%) in Build; VO2max (106-120%) in Peak.
   - Run: Daniels above.
   - Brick: bike-then-run, run leg = 15-30% of bike duration in Base, growing to 30-50% in Peak.

5. **Long-session progression within a phase.** Long-session duration ramps week-over-week within a block (e.g. Base: 60→75→90→back-off-60), then a deload, then continues building in next block.

6. **Recovery + deload.** Every 3rd or 4th week MUST be a back-off week (volume cut ~25%, intensity preserved). High weekly hours = more frequent deload (every 3 weeks); low hours = every 4 weeks.

7. **Race-specific taper.**
   - 5K/10K: 7-day taper, -30% volume.
   - Half Marathon: 10-14 day taper, -30% to -40%.
   - Marathon: 14-21 day taper, -40% to -50%.
   - Sprint Tri / Olympic Tri: 7-10 day taper, -30%.
   - Half Ironman: 14 day taper, -45%.
   - Full Ironman: 21 day taper, -50% week 1, -65% week 2, race week ~25% with race-pace primers.

═══ HARD CONSTRAINTS — MUST follow ═══

• Use ONLY the user's selected training days for sessions. Other days = full rest. Do not invent training days.
• **DISCIPLINE LOCK**: only prescribe session.type values from the user's availableDisciplines list. For run-only events (5K/10K/HM/Marathon) — even if the user has 'swim' or 'bike' in their list — DO NOT prescribe swim or bike on a primary quality day. Swim/bike are cross-training only when the event is a triathlon. For run events, every "quality" or "long" day is a RUN day.
• For run events: allowed types are {'run', 'rest', ${hasStrength ? "'strength'" : "/* no strength access */"}, 'mobility'}. Never 'swim', never 'bike' (unless explicitly cross-training in cases of injury, and even then label it as 'run' replacement, not a primary session).
• For triathlon events: types follow the discipline allocation rules in the discipline note.
• Total weekly minutes must be within ±15% of the user's stated weekly hours × 60. (User said ${hours} hrs/week → target ~${Math.round(hours * 60)} min/week.)
• Each week must have at least one full rest day (duration:0, type:'rest'). Two if hours <= 4.
• Quality (high-intensity) sessions must be spaced at least 48 hours apart, ideally 72.
• No week-over-week total-hours jump exceeds +25% or drops more than 35% (deload/taper aside).
• Long session is on Sat or Sun if those are training days; otherwise on the last selected day.
• Every session has: name, type (run/bike/swim/strength/brick/mobility/rest/quality), durationMin (integer), intensity ('Z2','Z3','Z4','Z5','mixed','rest'), prescription (1-2 sentence description of the workout structure), targets (HR/pace/RPE guidance — use ranges and reference the appropriate Daniels/CTL anchor when applicable).
• prescription MUST reference specific zones, drills, or intervals — not just "easy aerobic." E.g. "8x400m at I pace (~5K race pace) with 400m recoveries; 1mi WU + CD" not "intervals."
• prescription MUST be populated on every non-rest session — never leave it blank.

═══ DISCIPLINE NOTES FOR THIS USER ═══

Event: ${event}
${disciplineNote}
Weeks to race: ${weeksToRace || 'not provided — assume 16'}
Weekly hours: ${hours}
Training days: ${days.join(', ')}
Today: ${todayStr}
${location ? 'Race location: ' + location : ''}
${courseIntel && courseIntel.terrain ? 'Course terrain: ' + courseIntel.terrain : ''}
${courseIntel && courseIntel.climate ? 'Course climate: ' + courseIntel.climate : ''}
${profile && profile.exp ? 'Experience: ' + profile.exp : ''}
${profile && profile.injury ? 'Injury status: ' + profile.injury : ''}
${profile && profile.sleep ? 'Typical sleep: ' + profile.sleep : ''}${buildFitnessMarkersBlock(fitnessMarkers)}

═══ OUTPUT JSON SCHEMA — STRICT ═══

You MUST output an object exactly matching this shape:

{
  "summary": "1-2 sentence top-line: what the plan optimizes for, the methodology you applied",
  "blocks": [
    { "name": "Base 1", "weeks": [0,1,2], "focus": "aerobic base + neuromuscular form" },
    ...
  ],
  "weeks": [
    {
      "weekIndex": 0,
      "label": "Week 1 — Base 1",
      "phase": "Base",
      "weeklyTotalMin": 300,
      "intensityRatio": "82/18",
      "focus": "establish aerobic base, get into rhythm",
      "deload": false,
      "sessions": {
        "Mon": { "name": "Rest", "type": "rest", "durationMin": 0, "intensity": "rest", "prescription": "Full rest. Walk 20 min if you want.", "targets": "" },
        "Tue": { "name": "...", ... },
        ...
        "Sun": { ... }
      }
    },
    ... (one per week, weekIndex 0 through weeksToRace-1)
  ],
  "notesForUser": [
    "1-3 short bullet notes about the plan's logic that the user should know"
  ]
}

═══ FIELD CONSISTENCY — CRITICAL ═══

These fields are read by DIFFERENT parts of the UI. If they disagree, the user sees inconsistent info ("card says 15 min walk, modal says 40 min run") — which destroys trust.

• "name" — short label, 1-4 words. Examples: "Easy run", "Tempo intervals", "Long run", "Recovery walk-jog", "Strength + mobility", "Brick (bike + run)".
  ❌ NEVER include numbers, minutes, miles, pace, or HR. NO "15-min walk", NO "8x400m", NO "Z2". Those go in prescription/targets.
  ❌ NEVER include "min" or "minute" in the name.
• "durationMin" — single integer, the TOTAL minutes for the whole session including warmup + cooldown. The card and modal both read this directly. It MUST equal the time covered by your prescription text.
• "prescription" — full workout text. If you write "5 min walk WU + 8×(60s/90s) + 5 min CD ≈ 28 min", durationMin must equal that total (≈28). If durationMin is 40, the prescription must total 40 min.
• "intensity" — Z1/Z2/Z3/Z4/Z5 OR the word "rest" for rest days. One value per session.
• "type" — must match the actual workout: "run" if it's a run, "walk-run" beginner intervals are still type="run".

If you change durationMin, the prescription text must reflect the new total. If you change prescription structure, durationMin must follow. They are tied together.

NO prose outside this JSON. NO markdown. NO trailing comments. Just the object.`;
}

function buildUserPrompt({ event, hours, days, raceDate, weeksToRace, profile, courseIntel, triFocus, fitnessMarkers, availableDisciplines, difficultyAdjust, location }) {
  const limiter = (triFocus && triFocus.limiter) || '';
  const strategy = (triFocus && triFocus.strategy) || '';
  const discList = Array.isArray(availableDisciplines) && availableDisciplines.length > 0 ? availableDisciplines.join(', ') : '';
  return `Generate a complete periodized training plan for me.

Inputs:
- Event: ${event}
- Race date: ${raceDate || 'not set'}
- Weeks to race: ${weeksToRace}
- Weekly hours available: ${hours}
- Training days: ${days.join(', ')}
- Location: ${location || 'unspecified'}
${discList ? '- Available disciplines (only prescribe these): ' + discList : ''}
${courseIntel && courseIntel.terrain ? '- Course terrain: ' + courseIntel.terrain : ''}
${courseIntel && courseIntel.surface ? '- Course surface: ' + courseIntel.surface : ''}
${courseIntel && courseIntel.swim ? '- Swim type: ' + courseIntel.swim : ''}
${courseIntel && courseIntel.climate ? '- Course climate: ' + courseIntel.climate : ''}
${courseIntel && courseIntel.altitude ? '- Course altitude: ' + courseIntel.altitude : ''}
${profile && profile.exp ? '- Experience level: ' + profile.exp : ''}
${profile && profile.freq ? '- Recent training frequency: ' + profile.freq : ''}
${profile && profile.injury ? '- Injury status: ' + profile.injury : ''}
${profile && profile.sleep ? '- Sleep: ' + profile.sleep : ''}
${limiter && limiter !== 'balanced' ? '- WEAKNESS / limiter discipline: ' + limiter.toUpperCase() : ''}
${strategy ? '- Strategy on the limiter: ' + strategy : ''}

${limiter && limiter !== 'balanced' && strategy === 'focus' ? `IMPORTANT: I identified ${limiter.toUpperCase()} as my weakness and asked for a FOCUS strategy. Build the plan with disproportionate weekly time on ${limiter} per the rules in your system prompt. Don't water this down — I want to see ${limiter} as the largest discipline bucket every week.` : ''}

${discList && discList.includes('strength') ? 'I have strength/gym access — please include 1-2 specific strength sessions per week with concrete exercise prescriptions, phase-appropriate.' : ''}

${difficultyAdjust === 'easier' ? 'IMPORTANT: I told you my last plan was TOO HARD. Build the new plan with lighter sessions, longer walk intervals, slower progression. Defer quality work by 1-2 weeks. Treat me as a notch less experienced than my profile suggests.' : difficultyAdjust === 'harder' ? 'IMPORTANT: I told you my last plan was TOO EASY. Build the new plan with sharper progression, earlier quality work (week 3 instead of week 5), longer continuous run intervals from week 1. Treat me as a notch more experienced than my profile suggests.' : ''}

Build the full ${Math.min(weeksToRace || 16, 24)}-week (or fewer if less time) plan now. Output the JSON only.`;
}

// ─── Plan validation ─────────────────────────────────────────────────────

const VALID_TYPES = ['run','bike','swim','strength','brick','mobility','rest','quality'];
const DAYS_ORDER = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];

function validatePlan(parsed, { event, hours, days, weeksToRace, profile, fitnessMarkers }) {
  if (!parsed || typeof parsed !== 'object') return { ok: false, reason: 'plan is not an object' };
  if (typeof parsed.summary !== 'string') return { ok: false, reason: 'missing summary' };
  if (!Array.isArray(parsed.weeks) || parsed.weeks.length === 0) return { ok: false, reason: 'missing weeks array' };
  if (parsed.weeks.length > 30) return { ok: false, reason: 'plan too long (>30 weeks)' };

  const targetWeeklyMin = hours * 60;
  const minWeeklyMin = Math.round(targetWeeklyMin * 0.30);   // hard floor; deload/taper ok
  const maxWeeklyMin = Math.round(targetWeeklyMin * 1.30);   // hard ceiling
  const trainingDaySet = new Set(days);

  // For run-only events, the AI sometimes hallucinates swim/bike sessions
  // (training data leakage from triathlon plans). Coerce them back to run
  // here so the user gets a coherent run plan even if the AI slipped up.
  const isRunOnly = /Marathon|10K|5K|Half Marathon/i.test(event) && !/Triathlon|Ironman/i.test(event);
  const isShortRun = /\b(5K|10K)\b/i.test(event);
  const exp = profile && profile.exp;
  const runAbility = fitnessMarkers && fitnessMarkers.runAbility;
  const isBeginnerRunner = isShortRun && (exp === 'new' || runAbility === 'walk-run' || runAbility === 'under-15');
  // Hard session-duration cap for beginners on a 5K plan. The AI sometimes
  // fills the user's stated weekly hours with too-long sessions; cap each
  // session here regardless of what the AI prescribed.
  const beginnerSessionCapMin = (weekIdx) => {
    if (!isBeginnerRunner) return Infinity;
    if (weekIdx <= 1) return 32;      // weeks 1-2
    if (weekIdx <= 3) return 38;      // weeks 3-4
    return 45;                         // weeks 5+ — never beyond this for beginners
  };

  let prevWeekMin = null;
  for (let wi = 0; wi < parsed.weeks.length; wi++) {
    const wk = parsed.weeks[wi];
    if (!wk || typeof wk !== 'object') return { ok: false, reason: `week ${wi} is not an object` };
    if (!wk.sessions || typeof wk.sessions !== 'object') return { ok: false, reason: `week ${wi} missing sessions` };
    let weekMin = 0;
    let restCount = 0;
    let qualityDays = [];
    for (const dayName of DAYS_ORDER) {
      const sess = wk.sessions[dayName];
      if (!sess) return { ok: false, reason: `week ${wi} ${dayName} missing` };
      if (typeof sess.name !== 'string') sess.name = sess.name || 'Untitled';
      // Field consistency defense: strip duration/pace/distance numbers from name
      // so the card label doesn't conflict with durationMin shown beside it.
      // The prescription field is where numbers belong.
      sess.name = sanitizeSessionName(sess.name);
      if (typeof sess.durationMin !== 'number') sess.durationMin = 0;
      if (sess.durationMin < 0) sess.durationMin = 0;
      if (sess.durationMin > 360) return { ok: false, reason: `week ${wi} ${dayName} duration > 6h` };
      if (!VALID_TYPES.includes(sess.type)) sess.type = sess.durationMin === 0 ? 'rest' : 'run';
      // Run-only events: hard-coerce swim/bike/brick → run (with a note in
      // prescription so the user knows). The AI shouldn't have prescribed
      // these in the first place but we defend in depth.
      if (isRunOnly && (sess.type === 'swim' || sess.type === 'bike' || sess.type === 'brick')) {
        const original = sess.type;
        sess.type = 'run';
        sess.name = sess.name && !/run/i.test(sess.name) ? `Easy run (was ${original})` : (sess.name || 'Easy run');
        sess.prescription = (sess.prescription ? sess.prescription + ' ' : '') + `[Coerced from ${original} to run — this is a run-only event.]`;
      }
      // Beginner runner: cap any non-rest session at the week-appropriate max.
      // The AI keeps slipping into "fill the available hours" — defend in depth.
      const cap = beginnerSessionCapMin(wi);
      if (sess.durationMin > cap && sess.type !== 'rest') {
        const original = sess.durationMin;
        sess.durationMin = cap;
        sess.prescription = (sess.prescription ? sess.prescription + ' ' : '') + `[Capped from ${original} to ${cap} min — beginner-runner session limit for week ${wi + 1}. The remaining time is intentional rest, not missing.]`;
      }
      if (!sess.intensity) sess.intensity = sess.type === 'rest' ? 'rest' : 'Z2';
      if (typeof sess.prescription !== 'string') sess.prescription = '';
      if (typeof sess.targets !== 'string') sess.targets = sess.targets ? String(sess.targets) : '';
      // Non-training day enforcement — if user didn't pick this day, force it to rest.
      if (!trainingDaySet.has(dayName) && sess.durationMin > 0) {
        sess.durationMin = 0;
        sess.type = 'rest';
        sess.name = 'Rest';
        sess.intensity = 'rest';
        sess.prescription = 'Full rest day.';
        sess.targets = '';
      }
      weekMin += sess.durationMin;
      if (sess.type === 'rest' || sess.durationMin === 0) restCount++;
      if (sess.type === 'quality' || sess.type === 'brick' || (sess.intensity && /Z[345]/.test(sess.intensity))) {
        qualityDays.push(DAYS_ORDER.indexOf(dayName));
      }
    }
    if (restCount === 0) return { ok: false, reason: `week ${wi} has zero rest days` };
    // Quality spacing: any two quality days within 1 day of each other = rejection.
    for (let i = 1; i < qualityDays.length; i++) {
      if (qualityDays[i] - qualityDays[i - 1] === 1) {
        return { ok: false, reason: `week ${wi} has back-to-back quality days` };
      }
    }
    // Weekly volume sanity. Allow taper weeks below floor; flag if >ceiling.
    if (weekMin > maxWeeklyMin) return { ok: false, reason: `week ${wi} total ${weekMin}min exceeds ceiling ${maxWeeklyMin}` };
    // Week-over-week jump check (skip first week).
    if (prevWeekMin != null && weekMin > 0) {
      const ratio = weekMin / prevWeekMin;
      if (ratio > 1.30) return { ok: false, reason: `week ${wi} jumped ${Math.round((ratio - 1) * 100)}% over previous week` };
    }
    if (typeof wk.weeklyTotalMin !== 'number') wk.weeklyTotalMin = weekMin;
    prevWeekMin = weekMin;
  }
  return { ok: true, plan: parsed };
}

// ─── Helpers ──────────────────────────────────────────────────────────────

// Strip numbers, durations, paces, and distances from a session name so it's a
// pure label. Prevents the card showing "15-min walk" while the modal duration
// shows "40 min" — those numbers belong in prescription/targets, not name.
function sanitizeSessionName(raw) {
  if (typeof raw !== 'string') return 'Easy session';
  let s = raw.trim();
  // Common patterns to strip:
  //   "15-min ", "15 min ", "15min ", "15 minute ", "15-minute "
  //   "8x400m", "10x(2/1)", "30s ", "60s "
  //   "5K", "10K", "1 mile", "3mi"
  //   "Z2", "@RPE 6"
  s = s.replace(/\b\d+\s*(?:-)?\s*(?:min(?:ute)?s?|sec(?:ond)?s?|hr|hour|hrs|hours)\b\.?/gi, '');
  s = s.replace(/\b\d+\s*[x×]\s*\([^)]*\)/gi, '');           // "8x(60s/90s)"
  s = s.replace(/\b\d+\s*[x×]\s*\d+\s*[a-z]*/gi, '');         // "8x400m" / "6x3min"
  s = s.replace(/\b\d+\s*(?:k|km|mi|mile|miles|m)\b/gi, '');  // "5K", "3mi", "400m"
  s = s.replace(/\bZ[1-5]\b/gi, '');                           // zones
  s = s.replace(/\b(?:RPE|HR)\s*\d+(?:\s*-\s*\d+)?\b/gi, '');  // RPE/HR numbers
  s = s.replace(/\(\s*\)/g, '');                                // empty parens
  s = s.replace(/\s+/g, ' ').replace(/^[\s\-+:,]+|[\s\-+:,]+$/g, '').trim();
  // Title-case first letter for visual consistency.
  if (!s) return 'Easy session';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function jsonErr(status, message) {
  return new Response(JSON.stringify({ ok: false, error: message }), {
    status, headers: { 'Content-Type': 'application/json' },
  });
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error('timeout after ' + ms + 'ms')), ms);
    promise.then(v => { clearTimeout(t); resolve(v); }, e => { clearTimeout(t); reject(e); });
  });
}

function computeWeeksToRace(todayStr, raceDateStr) {
  if (!raceDateStr) return null;
  try {
    const today = new Date(todayStr + 'T00:00:00Z');
    const race = new Date(raceDateStr + 'T00:00:00Z');
    if (isNaN(race.getTime()) || isNaN(today.getTime())) return null;
    const days = Math.round((race - today) / (24 * 60 * 60 * 1000));
    if (days <= 0) return 0;
    return Math.max(1, Math.ceil(days / 7));
  } catch (e) { return null; }
}
